openapi: 3.0.1
info:
  description: '''dev2.baidu.com'' api schema'
  title: dev2 api schema
  version: 2023.0.0
servers:
- url: https://api.baidu.com/
- url: http://api.baidu.com/
tags:
- name: MaterialPersonModService
paths:
  json/sms/service/MaterialPersonModService/updateRank:
    post:
      operationId: updateRank
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UpdateRankRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UpdateRankResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: UpdateRankRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
  json/sms/service/MaterialPersonModService/addPerson:
    post:
      operationId: addPerson
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/AddPersonRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/AddPersonResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: AddPersonRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
  json/sms/service/MaterialPersonModService/updateCategory:
    post:
      operationId: updateCategory
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UpdateCategoryRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UpdateCategoryResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: UpdateCategoryRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
  json/sms/service/MaterialPersonModService/updatePutaway:
    post:
      operationId: updatePutaway
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UpdatePutawayRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UpdatePutawayResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: UpdatePutawayRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
  json/sms/service/MaterialPersonModService/updatePerson:
    post:
      operationId: updatePerson
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/UpdatePersonRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UpdatePersonResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: UpdatePersonRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
  json/sms/service/MaterialPersonModService/deletePerson:
    post:
      operationId: deletePerson
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/DeletePersonRequestWrapper'
        required: true
      responses:
        "200":
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/DeletePersonResponseWrapper'
          description: response
      tags:
      - MaterialPersonModService
      x-codegen-request-body-name: DeletePersonRequestWrapper
      x-contentType: application/json;charset=UTF-8
      x-accepts: application/json;charset=UTF-8
components:
  schemas:
    UpdatePutawayRequestWrapper:
      example:
        body:
          personIds:
          - 6
          - 6
          status: 0
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonBatchUpdatePutawayRequest'
      type: object
    ApiErrorInfo:
      type: object
    UpdateCategoryResponseWrapper:
      example:
        body:
          data:
          - 0
          - 0
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/UpdateCategoryResponseWrapperBody'
      type: object
    ApiRequestHeader:
      type: object
    UpdateRankResponseWrapper:
      example:
        body:
          data:
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/UpdateRankResponseWrapperBody'
      type: object
    DeletePersonResponseWrapper:
      example:
        body:
          data:
          - 0
          - 0
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/DeletePersonResponseWrapperBody'
      type: object
    DeletePersonRequestWrapper:
      example:
        body:
          personIds:
          - 0
          - 0
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonBatchIdRequest'
      type: object
    AddPersonRequestWrapper:
      example:
        body:
          educationBackground: educationBackground
          honour: honour
          goodAt: goodAt
          education: education
          gender: 2
          workingYears: 0
          profileImage: profileImage
          roleType: 5
          idNumber: idNumber
          qualification: qualification
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          name: name
          location: location
          job: job
          introduction: introduction
          categoryId: 6
          tradeId: 5
          status: 1
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonAddRequest'
      type: object
    UpdateCategoryRequestWrapper:
      example:
        body:
          personIds:
          - 6
          - 6
          categoryId: 0
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonBatchUpdateCategoryRequest'
      type: object
    TeslaPersonBatchUpdatePutawayRequest:
      example:
        personIds:
        - 6
        - 6
        status: 0
      properties:
        status:
          format: int32
          type: integer
        personIds:
          items:
            format: int64
            type: integer
          type: array
      type: object
    TeslaPersonUpdateRankRequest:
      example:
        rank: 0
        personId: 6
      properties:
        rank:
          format: int32
          type: integer
        personId:
          format: int64
          type: integer
      type: object
    ApiResponseHeader:
      type: object
    UpdateRankRequestWrapper:
      example:
        body:
          rank: 0
          personId: 6
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonUpdateRankRequest'
      type: object
    TeslaPersonUpdateRequest:
      example:
        educationBackground: educationBackground
        honour: honour
        goodAt: goodAt
        education: education
        gender: 7
        workingYears: 6
        profileImage: profileImage
        roleType: 2
        idNumber: idNumber
        qualification: qualification
        personExt:
          pracHospital: pracHospital
          representWork: representWork
          designConcept: designConcept
          constructionExperience: constructionExperience
          department: department
        name: name
        personId: 0
        location: location
        job: job
        introduction: introduction
        categoryId: 1
        tradeId: 5
        status: 5
      properties:
        personId:
          format: int64
          type: integer
        name:
          type: string
        profileImage:
          type: string
        job:
          type: string
        workingYears:
          format: int32
          type: integer
        goodAt:
          type: string
        education:
          type: string
        educationBackground:
          type: string
        introduction:
          type: string
        qualification:
          type: string
        categoryId:
          format: int64
          type: integer
        status:
          format: int32
          type: integer
        tradeId:
          format: int64
          type: integer
        roleType:
          format: int32
          type: integer
        personExt:
          $ref: '#/components/schemas/PersonExtDto'
        honour:
          type: string
        gender:
          format: int32
          type: integer
        idNumber:
          type: string
        location:
          type: string
      type: object
    TeslaPersonBatchIdRequest:
      example:
        personIds:
        - 0
        - 0
      properties:
        personIds:
          items:
            format: int64
            type: integer
          type: array
      type: object
    UpdatePutawayResponseWrapper:
      example:
        body:
          data:
          - 0
          - 0
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/UpdatePutawayResponseWrapperBody'
      type: object
    TeslaPersonAddRequest:
      example:
        educationBackground: educationBackground
        honour: honour
        goodAt: goodAt
        education: education
        gender: 2
        workingYears: 0
        profileImage: profileImage
        roleType: 5
        idNumber: idNumber
        qualification: qualification
        personExt:
          pracHospital: pracHospital
          representWork: representWork
          designConcept: designConcept
          constructionExperience: constructionExperience
          department: department
        name: name
        location: location
        job: job
        introduction: introduction
        categoryId: 6
        tradeId: 5
        status: 1
      properties:
        name:
          type: string
        profileImage:
          type: string
        job:
          type: string
        workingYears:
          format: int32
          type: integer
        goodAt:
          type: string
        education:
          type: string
        educationBackground:
          type: string
        introduction:
          type: string
        qualification:
          type: string
        categoryId:
          format: int64
          type: integer
        status:
          format: int32
          type: integer
        tradeId:
          format: int64
          type: integer
        roleType:
          format: int32
          type: integer
        personExt:
          $ref: '#/components/schemas/PersonExtDto'
        honour:
          type: string
        gender:
          format: int32
          type: integer
        idNumber:
          type: string
        location:
          type: string
      type: object
    TeslaPersonBatchUpdateCategoryRequest:
      example:
        personIds:
        - 6
        - 6
        categoryId: 0
      properties:
        categoryId:
          format: int64
          type: integer
        personIds:
          items:
            format: int64
            type: integer
          type: array
      type: object
    UpdatePersonRequestWrapper:
      example:
        body:
          educationBackground: educationBackground
          honour: honour
          goodAt: goodAt
          education: education
          gender: 7
          workingYears: 6
          profileImage: profileImage
          roleType: 2
          idNumber: idNumber
          qualification: qualification
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          name: name
          personId: 0
          location: location
          job: job
          introduction: introduction
          categoryId: 1
          tradeId: 5
          status: 5
      properties:
        header:
          $ref: '#/components/schemas/ApiRequestHeader'
        body:
          $ref: '#/components/schemas/TeslaPersonUpdateRequest'
      type: object
    UpdatePersonResponseWrapper:
      example:
        body:
          data:
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/UpdatePersonResponseWrapperBody'
      type: object
    PersonExtDto:
      example:
        pracHospital: pracHospital
        representWork: representWork
        designConcept: designConcept
        constructionExperience: constructionExperience
        department: department
      properties:
        representWork:
          type: string
        designConcept:
          type: string
        constructionExperience:
          type: string
        pracHospital:
          type: string
        department:
          type: string
      type: object
    AddPersonResponseWrapper:
      example:
        body:
          data:
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
          - goodAt: goodAt
            education: education
            gender: 9
            workingYears: 6
            profileImage: profileImage
            roleType: 7
            idNumber: idNumber
            categoryName: categoryName
            personExt:
              pracHospital: pracHospital
              representWork: representWork
              designConcept: designConcept
              constructionExperience: constructionExperience
              department: department
            rank: 5
            reauditStatus: 3
            introduction: introduction
            educationBackground: educationBackground
            honour: honour
            auditRemark: auditRemark
            updateTime: updateTime
            qualification: qualification
            createTime: createTime
            name: name
            personId: 0
            location: location
            job: job
            categoryId: 1
            tradeId: 2
            status: 5
      properties:
        header:
          $ref: '#/components/schemas/ApiResponseHeader'
        body:
          $ref: '#/components/schemas/AddPersonResponseWrapperBody'
      type: object
    PersonDetailDto:
      example:
        goodAt: goodAt
        education: education
        gender: 9
        workingYears: 6
        profileImage: profileImage
        roleType: 7
        idNumber: idNumber
        categoryName: categoryName
        personExt:
          pracHospital: pracHospital
          representWork: representWork
          designConcept: designConcept
          constructionExperience: constructionExperience
          department: department
        rank: 5
        reauditStatus: 3
        introduction: introduction
        educationBackground: educationBackground
        honour: honour
        auditRemark: auditRemark
        updateTime: updateTime
        qualification: qualification
        createTime: createTime
        name: name
        personId: 0
        location: location
        job: job
        categoryId: 1
        tradeId: 2
        status: 5
      properties:
        personId:
          format: int64
          type: integer
        name:
          type: string
        profileImage:
          type: string
        job:
          type: string
        workingYears:
          format: int32
          type: integer
        goodAt:
          type: string
        education:
          type: string
        educationBackground:
          type: string
        introduction:
          type: string
        qualification:
          type: string
        categoryId:
          format: int64
          type: integer
        categoryName:
          type: string
        status:
          format: int32
          type: integer
        auditRemark:
          type: string
        rank:
          format: int32
          type: integer
        createTime:
          type: string
        updateTime:
          type: string
        tradeId:
          format: int64
          type: integer
        roleType:
          format: int32
          type: integer
        personExt:
          $ref: '#/components/schemas/PersonExtDto'
        honour:
          type: string
        gender:
          format: int32
          type: integer
        idNumber:
          type: string
        location:
          type: string
        reauditStatus:
          format: int32
          type: integer
      type: object
    UpdateCategoryResponseWrapperBody:
      example:
        data:
        - 0
        - 0
      properties:
        data:
          items:
            format: int64
            type: integer
          type: array
      title: UpdateCategoryResponseWrapperBody
      type: object
    UpdateRankResponseWrapperBody:
      example:
        data:
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
      properties:
        data:
          items:
            $ref: '#/components/schemas/PersonDetailDto'
          type: array
      title: UpdateRankResponseWrapperBody
      type: object
    DeletePersonResponseWrapperBody:
      example:
        data:
        - 0
        - 0
      properties:
        data:
          items:
            format: int64
            type: integer
          type: array
      title: DeletePersonResponseWrapperBody
      type: object
    UpdatePutawayResponseWrapperBody:
      example:
        data:
        - 0
        - 0
      properties:
        data:
          items:
            format: int64
            type: integer
          type: array
      title: UpdatePutawayResponseWrapperBody
      type: object
    UpdatePersonResponseWrapperBody:
      example:
        data:
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
      properties:
        data:
          items:
            $ref: '#/components/schemas/PersonDetailDto'
          type: array
      title: UpdatePersonResponseWrapperBody
      type: object
    AddPersonResponseWrapperBody:
      example:
        data:
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
        - goodAt: goodAt
          education: education
          gender: 9
          workingYears: 6
          profileImage: profileImage
          roleType: 7
          idNumber: idNumber
          categoryName: categoryName
          personExt:
            pracHospital: pracHospital
            representWork: representWork
            designConcept: designConcept
            constructionExperience: constructionExperience
            department: department
          rank: 5
          reauditStatus: 3
          introduction: introduction
          educationBackground: educationBackground
          honour: honour
          auditRemark: auditRemark
          updateTime: updateTime
          qualification: qualification
          createTime: createTime
          name: name
          personId: 0
          location: location
          job: job
          categoryId: 1
          tradeId: 2
          status: 5
      properties:
        data:
          items:
            $ref: '#/components/schemas/PersonDetailDto'
          type: array
      title: AddPersonResponseWrapperBody
      type: object
x-original-swagger-version: "2.0"

